[project]
name = "whatsapp-aunite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.6.2",
    "dotenv>=0.9.9",
    "flask>=3.1.1",
    "openai-agents>=0.2.0",
    "twilio>=9.6.5",
]
