[project]
name = "class-four"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "browser-use>=0.4.4",
    "dotenv>=0.9.9",
    "langchain-google-genai>=2.1.6",
    "openai-agents>=0.1.0",
]
